### ISSUE TITLE
format for ids

### ISSUE THREAD

**Issue by koykoy027** [Real-Faith-Solutions/aqua-lab-ph-management-system#37]
- [x] client_id
- `00-AA-11-22-BBB-333`
- 00 - area code
- AA - two letter of city
- 11 - month generated
- 22 - year generated
- BBB - market segment
- 333 - running number of segment

---
- [x] analysis_id and sample_id
- `A-02-01`
- A - first letter of the month
- 02 - date receive
- 01 - continues number

---
- [x] certificate_no
8 DIGITS + TWO CHARACTER (ML or CL) 
- FIRST TWO DIGITS - LAST TWO DIGITS OF THE CURRENT YEAR (E.G. 2023 - 23)
- 3RD-8TH DIGITS - SERIES BEGINNING 000001
- LAST TWO CHARACTER - ML if issued by MICRO LAB or CL if issued by CHEM LAB

**Comment by thrustyvector** [comment]
Hi, just a beginner, can you assign me with one good first issue

**Comment by koykoy027** [comment]
done
